### ISSUE TITLE
Feature Idea: Webscrapping either by using urlid or tag

### ISSUE THREAD

**Issue by shitalmule04** [pythonpune/readit#102]
To make the availability of bookmarked URL contents locally/offline. Lets add one more feature i.e.Download the content of bookmarked URL either by urlid or tag. Also, while downloading content it must show the download progress.

Following options, we can consider:

- Using urlid:

> readit -dwl urlid
> readit --download urlid

- Using tag:

> readit -dwlt tag
> readit --downloadt tag

**Comment by shitalmule04** [comment]
I am working on this issue.

**Comment by ganeshhubale** [comment]
Currently, we check if url is accessible or not using requests library. and thus we ask use if user wants to bookmark it or not.
Closing this issue as we do not need this feature.
