### ISSUE TITLE
[RFE] User should able to add url and tag both at a time

### ISSUE THREAD

**Issue by amolkahat** [pythonpune/readit#122]
Currently, it is not implemented that user should add both tag and url at the same time. 
Case 1:
Suppose if user want to add URL and tag, and should display the message.
```
readit -a https://google.com -t search_engine
Bookmarked.
URL tagged to search_engine tag.
```
Case 2:
If tag is already present then user should able to add it to that tag.
```
readit -a https://opensource.com -t magazine
Bookmarked.
URL tagged to magazine tag.
```

**Comment by san7ket** [comment]
Can I pick this?
