### ISSUE TITLE
User should be able to specify path for exported bookmarked urls file

### ISSUE THREAD

**Issue by ganeshhubale** [pythonpune/readit#139]
- Now **readit** tool directly gives the path of exported file after executing ```readit -e``` .
- This issue demands that **user should have freedom of choosing the destination path for newly created exported bookmarks file**.

**Comment by vishalbidwe** [comment]
I would like to work on it.

**Comment by ganeshhubale** [comment]
if you need more information related to this issue.
Please let me know.
Also you can add your own points/views about this issue here.

**Comment by vishalbidwe** [comment]
we can use Tkinter for file saving dialog , suggestions?

**Comment by ganeshhubale** [comment]
@vishalbidwe 
You can go ahead with this solution. Just let me know the way, you  are going to implement it.
So please mention explanation or steps of your solution.
Thank you.
