### ISSUE TITLE
sudo should be avoided while installing dependencies 

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#15]
This section from `README.md` https://github.com/ganeshhubale/readit#dependencies
Instructus users to install packages with `sudo pip ...` which should be avoided.

Explanation: https://stackoverflow.com/a/37104948

**Comment by ganeshhubale** [comment]
#15 fixed by 5604c8e .

**Comment by bhavin192** [comment]
If `sudo` is removed you will get error while installing the dependencies.
Please read the answer from Stackoverflow. Also please reopen this issue. 
It would be great if we work by sending PR

**Comment by bhavin192** [comment]
I strongly recommend using virtualenv and install the dependencies there instead of installing them globally.

**Comment by ganeshhubale** [comment]
yes, using virtualenv would be good. I had used it for installation.

**Comment by ganeshhubale** [comment]
i have updated in README file by  42e6921 . please review.

**Comment by bhavin192** [comment]
@ganeshhubale It is better to review a PR, can you please create a PR for the solution of this issue?

**Comment by bhavin192** [comment]
@ganeshhubale doing `sudo pip install` can also break `dnf` on Fedora 
https://fedoraproject.org/wiki/Changes/Making_sudo_pip_safe

**Comment by bhavin192** [comment]
Now we have `setup.py` to handle dependencies. Closing this one.
