### ISSUE TITLE
OperationalError while searching URLs by tag

### ISSUE THREAD

**Issue by ganeshhubale** [pythonpune/readit#159]
Steps
- Python3.7.5
- Add URLs with same tag
- Search URL by tag

```
(n) [ghubale@localhost readit]$ readit -s mytag
Traceback (most recent call last):
  File "/home/ghubale/readit/readit/readit/database.py", line 193, in search_url
    (self.search),
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 5 supplied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ghubale/readit/n/bin/readit", line 11, in <module>
    load_entry_point('readit', 'console_scripts', 'readit')()
  File "/home/ghubale/readit/n/lib64/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ghubale/readit/n/lib64/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ghubale/readit/n/lib64/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ghubale/readit/n/lib64/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ghubale/readit/readit/readit/cli.py", line 130, in main
    output.print_bookmarks(database_connection.search_url(search))
  File "/home/ghubale/readit/readit/readit/database.py", line 208, in search_url
    raise sqlite3.OperationalError
sqlite3.OperationalError
(n) [ghubale@localhost readit]$ 
```

**Comment by SurajJadhav7** [comment]
Python 3.8.2

It's working as necessary.

`s@pc:~$ readit -s tag1
/home/s/.local/lib/python3.8/site-packages/beautifultable/beautifultable.py:362: FutureWarning: 'left_border_char' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. None
  warnings.warn(
/home/s/.local/lib/python3.8/site-packages/beautifultable/beautifultable.py:362: FutureWarning: 'right_border_char' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. None
  warnings.warn(
/home/s/.local/lib/python3.8/site-packages/beautifultable/beautifultable.py:362: FutureWarning: 'top_border_char' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. None
  warnings.warn(
/home/s/.local/lib/python3.8/site-packages/beautifultable/beautifultable.py:362: FutureWarning: 'header_separator_char' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. None
  warnings.warn(
/home/s/.local/lib/python3.8/site-packages/beautifultable/utils.py:113: FutureWarning: 'BeautifulTable.column_headers' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. Use 'BTColumnCollection.header' instead.
  warnings.warn(message, FutureWarning)
************************ 
Already bookmarked URLs.
 ***********************
/home/s/.local/lib/python3.8/site-packages/beautifultable/utils.py:113: FutureWarning: 'BeautifulTable.append_row' has been deprecated in 'v1.0.0' and will be removed in 'v1.2.0'. Use 'BTRowCollection.append' instead.
  warnings.warn(message, FutureWarning)
+----+----------------------------------------+------+------------+----------+
| ID |                  URL                   | TAG  |    DATE    |   TIME   |
+----+----------------------------------------+------+------------+----------+
| 3  |        https://meet.google.com/        | tag1 | 2020-11-18 | 12:02:25 |
+----+----------------------------------------+------+------------+----------+
| 4  |       https://web.whatsapp.com/        | tag1 | 2020-11-18 | 12:02:40 |
+----+----------------------------------------+------+------------+----------+
| 5  | https://github.com/SurajJadhav7/readit | tag1 | 2020-11-18 | 12:04:02 |
+----+----------------------------------------+------+------------+----------+`

**Comment by ganeshhubale** [comment]
I can still experience this issue with python3.7.5
But as this is working fine with the latest python version. Hence I am closing this issue.
Thank you @SurajJadhav7
