### ISSUE TITLE
No link to license in the README.md

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#16]
`README.md` should have link to full License text. 
Link to [LICENSE](https://github.com/ganeshhubale/readit/blob/master/LICENSE) file from the repo should be there.

**Comment by ganeshhubale** [comment]
#16 fixed

**Comment by bhavin192** [comment]
@ganeshhubale #16 fixed but by which commit?

**Comment by ganeshhubale** [comment]
#16 fixed by  6cb8a23

**Comment by bhavin192** [comment]
Can you please reopen? Cause the license is MIT and there is no link to the text MIT

**Comment by ganeshhubale** [comment]
I have linked to LICENSE text.

**Comment by bhavin192** [comment]
In my opinion the full license text should be linked to the name of license in our case 'MIT'

**Comment by bhavin192** [comment]
The best way would be write something like this,

readit is licensed under MIT. See [LICENSE](https://github.com/ganeshhubale/readit/blob/master/LICENSE) for the full license text.

**Comment by ganeshhubale** [comment]
fixed by 3f8f107.
