### ISSUE TITLE
Switch to GNU GPL v3

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#17]
Should we change the license of project to [`GNU GPL v3`](https://www.gnu.org/licenses/gpl-3.0.en.html) instead of `MIT`?

**Comment by ganeshhubale** [comment]
Yes, we can but can you please explain why do we need to switch?

**Comment by bhavin192** [comment]
GNU GPL is more restrictive, you can read the difference here
https://stackoverflow.com/a/11752204

**Comment by ganeshhubale** [comment]
#17 fixed by 718e753  .
