### ISSUE TITLE
Use latest Ubuntu images for Travis

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#20]
Right now we are using `group: deprecated-2017Q4`
https://github.com/ganeshhubale/readit/blob/master/.travis.yml#L12

This should be removed so that it will use latest Ubuntu images.

**Comment by ganeshhubale** [comment]
Yes, I too have validated on http://lint.travis-ci.org.

**Comment by ganeshhubale** [comment]
after validation error occured:  your repository must be feature flagged for the group setting to be used

**Comment by ganeshhubale** [comment]
#22 
- removed `group: deprecated-2017Q4`
