### ISSUE TITLE
python files should be reformat as per pep8 standards

### ISSUE THREAD

**Issue by shitalmule04** [pythonpune/readit#29]
`Travis-ci` building is falling because of files with `.py` extension, not fallow the `flake8` standards. This can be solved by using `autopep8`.

**Comment by shitalmule04** [comment]
@bhavin192, please review the changes.

**Comment by ganeshhubale** [comment]
@shitalmule04 
- please correct the title of the issue. 
- also it has a spelling mistake: **reforamat** must change to **reformat** .
- Don't need to specify tools in title.

**Comment by ganeshhubale** [comment]
@shitalmule04 
- please read the previous comment carefully.
- I am telling you to change title, it doesn't make any sense.

**Comment by shitalmule04** [comment]
@ganeshhubale, This done from my side.

**Comment by shitalmule04** [comment]
All work regarding #29 is done  at issue added requests library #31

**Comment by shitalmule04** [comment]
@ganeshhubale, Its done from my side.
