### ISSUE TITLE
Improve readability of code

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#46]
We need to improve readability of code 
Like instead of 
```Python
import datetime as dt
```
using `datetime` directly makes it more readable 
similarly at some places there are variables like `u`, `r` 
let's rename them to something like `url_of_something` 
for this one 
```Python 
for i in add:
```
https://github.com/ganeshhubale/readit/blob/master/manager/readit.py#L24
we can write it as 

```Python 
for url_to_add in add:
```

**Comment by ganeshhubale** [comment]
@bhavin192 
I have worked on it. I tried to make whole code readable. Please take a look at it.

**Comment by bhavin192** [comment]
@ganeshhubale please try to make one PR for one issue. It's really hard to review your changes related to one particular issue from bunch of commits.
