### ISSUE TITLE
Release v0.1 

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#50]
Release the v0.1 of the tool on
- GitHub 
- PyPI

Check list:
- [x] Make code compatible with Python 3 #51 
- [x] Create and maintain `CHANGELOG.md` 
- [x] Rename `manager` to `readit` #54

**Comment by bhavin192** [comment]
It's released now,
https://github.com/ganeshhubale/readit/releases/tag/v0.1

**Comment by ganeshhubale** [comment]
@bhavin192 
Thank you for your great contribution to **readit**.
