### ISSUE TITLE
Convert README.md to ReStructuredText

### ISSUE THREAD

**Issue by ganeshhubale** [pythonpune/readit#58]
As we have released `readit v0.1` by uploading [**readit**](https://pypi.python.org/pypi/readit) project on [PyPI](https://pypi.python.org/pypi/). We got to know that PyPI does not support `.md` file but it supports `.rst` files. So we need to convert `README.md` to `README.rst`.

**Comment by ganeshhubale** [comment]
@daivshala 
Can you explain, why do we need to convert `CHANGELOG.md` to ReStructuredText?

**Comment by daivshala** [comment]
@ganeshhubale   please  refer  [this link](https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work) .
and also go through [this project link](https://github.com/jakubroztocil/httpie).

**Comment by ganeshhubale** [comment]
@daivshala 
- Right now we are focusing on well written README file to attach it with PyPI.
- We will create [new file](https://github.com/ulif/diceware/blob/master/CHANGES.rst) which will include changes in project for every release.
