### ISSUE TITLE
'test.db' is created in current directory 

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/readit#60]
#### General information

  - readit version: `v0.1`
  - OS: `Fedora 27`
  - Installation method: All

#### Steps to reproduce

1. run the command `$ readit`
2. do `ls` in the same directory 
3. `cd` into different directory and repeat the 1 and 2

The file `test.db` should be stored somewhere else instead of the current directory.
We may store it in the same path where the `.py` file exist 
or somewhere in the home folder of user (this would be better I think)
Also we should consider renaming the file to something more appropriate, may be something like `readit-database`

**Comment by ganeshhubale** [comment]
@bhavin192 Thank you, It's very helpful.
- If we modify ` ~/.config/readit/somenamefordb.db` then it will be like `/home/current_username/.config/readit/somenamefordb.db`.
- So, we need to get `current_username`(using **getpass** module) from system and we can simply create above path with new folder `readit` and database name `bookmarks`(using **os** module) 

please let me know if you have any other suggestions.

**Comment by bhavin192** [comment]
>So, we need to get current_username(using getpass module)

what if the user has different home directory than `/home/user_name`
see `useradd` man page, the option `-d`

**Comment by ganeshhubale** [comment]
Code:

```
    import os
    username = 'test'
    password = 'test1234'
    os.system("useradd -d /home/%s -m -p %s %s" % (username, password, username))
    os.system("passwd %s" % username)
```
Error:
```
useradd: Permission denied.
useradd: cannot lock /etc/passwd; try again later.
256

```
I aplied above code but it shows permission denied because i am not on `root` user.
- it needs to log in to  `root` user, so that it can get permission to add user.
- it means if we have added above code to project then user need to install it in root user.
please let me know your views.
Ref. - https://www.daniweb.com/programming/software-development/threads/253341/linuxes-command-in-python-scripts

**Comment by bhavin192** [comment]
@ganeshhubale 
**What?** 
Why are you creating a new user, are you okay?

**Comment by ganeshhubale** [comment]
@bhavin192 
can you please explain, how should I go ahead?

**Comment by bhavin192** [comment]
@ganeshhubale I never said you have to create a new user (which makes no sense) 
The thing I wanted to say https://github.com/projectreadit/readit/issues/60#issuecomment-368831953 was, what if the user has different home directory than `/home/user_name` let's say `/opt/somedir`

solution would be to find actual home directory of user.

**Comment by ganeshhubale** [comment]
@bhavin192 
below code will help us to find home directory of current user.
```
>>> import os
>>> os.path.expanduser('~')
'/home/ganesh'

```
Ref.: https://stackoverflow.com/a/10170444/6807255
