### ISSUE TITLE
README.rst should be accessible to PyPI

### ISSUE THREAD

**Issue by ganeshhubale** [pythonpune/readit#66]
- It will help to show content of README file on PyPI as an information of **readit** project
- PyPI gets content directly from setup file which is assigned to `long description ` variable

**Comment by bhavin192** [comment]
If I haven't mistaken, the `long_description` variable is already getting set to content of `README.rst`, That's why it was picked by PyPI in last release. I don't see any need to change that.

https://github.com/projectreadit/readit/blob/039e2b7209085bc8b2ebb63cc95a2ac085e20b43/setup.py#L3-L4

**Comment by ganeshhubale** [comment]
@bhavin192 
Yes, true I will close this issue and respective PR #67.
