### ISSUE TITLE
How to open URL stored in it

### ISSUE THREAD

**Issue by ghost** [pythonpune/readit#73]
Hey folks
I have seen your project that's good and nice idea
I am very much worried about how to open URL which is stored in it and I want to set default internet browser for that particular link.

**Comment by shitalmule04** [comment]
@Sidd501, Even if the browser is closed, after prompting `$ readit -o urlid` or
`$ readit --openurl urlid` URL gets open in by default browser(i. e. Mozilla Firefox for Fedora OS). 

Thanks.
