### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by ganeshhubale** [pythonpune/readit#74]
- Resize the image
- Fast forward the video
- I got WARNING while performing `rst2html README.rst output.html`
```
README.rst:174: (WARNING/2) Title underline too short.

`Licence <https://github.com/projectreadit/readit/blob/master/LICENSE>`_
***********************************************************************
README.rst:174: (WARNING/2) Title underline too short.

`Licence <https://github.com/projectreadit/readit/blob/master/LICENSE>`_
```

**Comment by shitalmule04** [comment]
I am looking for adding HTML code in the file with` .rst` extension, so it will be easy to `Resize the image`.

**Comment by bhavin192** [comment]
@shitalmule04 you need to find a native way to do that in `.rst`

**Comment by shitalmule04** [comment]
Yes, @bhavin192, I have tried by taking reference of [this](http://docutils.sourceforge.net/docs/ref/rst/directives.html#images) link, but not supporting `width` parameter.

**Comment by bhavin192** [comment]
@ganeshhubale image is not resized yet, so I think this issue should not be closed.

**Comment by ganeshhubale** [comment]
@bhavin192 
It can't be resized using rst? height and width attributes are not taken.
Tried with html code too but not worked.

**Comment by bhavin192** [comment]
@ganeshhubale then try to find the solution,  it's possible to resize the image, that's why the option is there.

**Comment by ganeshhubale** [comment]
@shitalmule04
Find out solution for resizing image otherwise give proper reason.

**Comment by ganeshhubale** [comment]
@shitalmule04  
- Add **export** option in `README.md` file
- Please give updates asap.

**Comment by daivshala** [comment]
@shitalmule04 
add the Badge For documentation in README.rst file , refer #76 PR

**Comment by shitalmule04** [comment]
@ganeshhubale, @daivshala Done with adding the export feature related information and **docs badge** in README.rst

**Comment by ganeshhubale** [comment]
What is the progress about image resizing.

**Comment by bhavin192** [comment]
@shitalmule04 If I remember correctly, it's not needed to have separate Python file to do image resize.

Read this,
http://www.sphinx-doc.org/en/stable/rest.html#directives

http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

**Comment by shitalmule04** [comment]
@bhavin192, Probably I am mistaken and try to figure out the solution using `PILLOW` and `PIL`. I'll read and work out on the given references.
Thanks!
